/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rubber_duck.glb 
Author: Ikki_3d (https://sketchfab.com/ikki_3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rubber-duck-f1de4fc390db4266a509b9739350512a
Title: Rubber duck
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Duck(props) {
  const { nodes, materials } = useGLTF('/models/rubber_duck.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.material} position={[0, 173.286, -2.915]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.901, 1.086, 1.022]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/rubber_duck.glb')
